/** Generated by YAKINDU Statechart Tools code generator. */
package yakinduproject.modelloecommerce;

import yakinduproject.IStatemachine;

public interface IModelloEcommerceStatemachine extends IStatemachine {
	public interface SCInterface {
	
		public void raiseSwitchOn();
		
		public void raiseGo();
		
		public void raiseAdd();
		
		public void raiseExit1();
		
		public void raiseExit2();
		
		public void raiseProcede();
		
		public void raiseDecision();
		
		public void raiseReset();
		
		public void raiseRefuse();
		
		public void raiseOut1();
		
		public void raiseRecharge();
		
		public long getNumProducts();
		
		public void setNumProducts(long value);
		
		public long getMoney();
		
		public void setMoney(long value);
		
		public long getCosto();
		
		public void setCosto(long value);
		
	}
	
	public SCInterface getSCInterface();
	
}
